version: '3.9'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db

  db: 
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=letter-track
      - POSTGRES_USER=ap1
      - POSTGRES_PASSWORD=ap1
    volumes:
      - letter-track-pgdata:/var/lib/postgresql/data
    
volumes:
  letter-track-pgdata: 
    name: "letter-track-pgdata"